### ISSUE TITLE
Force の発散問題

### ISSUE THREAD

**Issue by Zabutonium** [Zabutonium/Comphys3-asign-team#11]
plot を行い振る舞いを観察してみたところ，計算自体はうまく働いているようですが，座標の近い particle どうしで力が発散し，急激にぴょーーーんと飛んでいってしまう描像が現れてしまっています。N>>1だとわかりにくいですが，N=2などでplotしてみますと顕著です。実際の plot は plotdata ディレクトリ下にあるので，ご確認ください。

この発散は力の計算を素朴に1/r^3としているためですが，この現象を回避する方法を模索中です。

**Comment by dedede-dede** [comment]
時間の刻みが荒すぎるんかな

**Comment by Zabutonium** [comment]
LINEでも言いましたが、この発散を回避させるための工夫として Softing Parameter の導入を行います。力を計算する際に発散の起きる原点を微小にズラすことで発散を finite に抑える手法で、この処方箋を採用したいと思います。
