### ISSUE TITLE
計算結果にNaNが出力されてしまう

### ISSUE THREAD

**Issue by Zabutonium** [Zabutonium/Comphys3-asign-team#9]
大方のプログラムは完成したのですが，計算結果にNaN(非数字であることを示すもの。）が表示されてしまう問題が発生しています。原因としてはゼロ除算などが挙げられますが，inputfileに用いているプログラムは座標の重複が無いようにparticleを置いていくようにしてあるためそのようなことは起こり得ないと考えられます。したがってleap-frog法の部分に問題があると思われますが，原因は未だ掴めていません。目下調査中です。進捗が進み次第追記いたします。

**Comment by dedede-dede** [comment]
NaNの件generateInitial_grid.cppでN=100になってるのが原因でした
